-- Pages de contenu initiales (FR/AR), éditables en back-office.
-- Textes originaux CivicCare Tunis : aucune reprise des textes juridiques de Munich.
-- Les coordonnées de l'exploitant sont des espaces réservés de démonstration à compléter
-- avant tout usage public. Aucune conformité juridique n'est certifiée.

INSERT INTO content_page (id, slug, title_fr, title_ar, body_fr, body_ar, updated_at) VALUES
('d0000000-0000-0000-0000-000000000001', 'faq',
 'Questions fréquentes', 'الأسئلة الشائعة',
 E'Comment déposer un signalement ?\nUtilisez le bouton « Signaler un problème », placez le point sur la carte, choisissez le type, décrivez le problème et indiquez votre e-mail. Aucun compte n''est nécessaire.\n\nQue deviennent mes coordonnées ?\nVotre e-mail et votre téléphone restent privés et ne sont jamais publiés. Ils servent uniquement au traitement de votre signalement et sont supprimés automatiquement 90 jours après la clôture (choix de démonstration configurable).\n\nPourquoi mon signalement n''est-il pas visible ?\nChaque signalement est vérifié avant publication. Un signalement non publié est néanmoins transmis et traité.\n\nComment suivre un signalement ?\nSur la fiche d''un signalement, utilisez « Suivre » pour l''enregistrer sur cet appareil, ou abonnez-vous par e-mail : l''abonnement ne devient actif qu''après confirmation par lien.\n\nQue signifie « traité ou intervention commandée » ?\nLe dossier est traité ou une intervention a été commandée auprès de l''équipe compétente. Cela ne garantit pas que le problème soit déjà physiquement réparé.\n\nPuis-je rechercher un signalement précis ?\nOui, par sa référence (par exemple 000123-2026) ou par un mot de sa description, en français ou en arabe.',
 E'كيف أودع تبليغاً؟\nاستعملوا زر « الإبلاغ عن مشكلة »، ضعوا النقطة على الخريطة، اختاروا النوع، صفوا المشكلة وأدخلوا بريدكم الإلكتروني. لا حاجة إلى حساب.\n\nماذا يحدث لبياناتي؟\nيبقى بريدكم وهاتفكم خاصين ولا يُنشران أبداً. يُستعملان فقط لمعالجة تبليغكم ويُحذفان تلقائياً بعد 90 يوماً من الإغلاق (خيار تجريبي قابل للتعديل).\n\nلماذا لا يظهر تبليغي؟\nيُراجع كل تبليغ قبل نشره. التبليغ غير المنشور يُحال ويُعالج رغم ذلك.\n\nكيف أتابع تبليغاً؟\nفي صفحة التبليغ، استعملوا « متابعة » لحفظه على هذا الجهاز، أو اشتركوا بالبريد الإلكتروني: لا يصبح الاشتراك نشطاً إلا بعد التأكيد عبر الرابط.\n\nماذا تعني « تمت المعالجة أو صدر أمر بالتدخل »؟\nتمت معالجة الملف أو صدر أمر بالتدخل للفريق المختص. هذا لا يضمن أن المشكلة أُصلحت مادياً بعد.\n\nهل يمكنني البحث عن تبليغ محدد؟\nنعم، بمرجعه (مثلاً 000123-2026) أو بكلمة من وصفه، بالفرنسية أو بالعربية.',
 now()),

('d0000000-0000-0000-0000-000000000002', 'how',
 'Fonctionnement du service', 'كيفية عمل الخدمة',
 E'1. Vous localisez le problème sur la carte de Tunis et choisissez son type parmi le catalogue.\n2. Vous décrivez le problème et joignez jusqu''à trois photos facultatives.\n3. Vous indiquez votre e-mail (privé) et validez le consentement.\n4. Le signalement est vérifié par la modération puis publié et transmis à l''équipe de traitement compétente.\n5. Vous suivez l''avancement : ouvert, en traitement, traité ou intervention commandée, ou hors compétence municipale.\n\nCe service est une application de démonstration : les équipes de traitement sont fictives et aucun dossier n''est transmis à une autorité réelle.',
 E'1. تحددون موقع المشكلة على خريطة تونس وتختارون نوعها من الفهرس.\n2. تصفون المشكلة وترفقون حتى ثلاث صور اختيارية.\n3. تدخلون بريدكم الإلكتروني (خاص) وتؤكدون الموافقة.\n4. يُراجع التبليغ ثم يُنشر ويُحال إلى فريق المعالجة المختص.\n5. تتابعون التقدم: مفتوح، قيد المعالجة، تمت المعالجة أو صدر أمر بالتدخل، أو خارج اختصاص البلدية.\n\nهذه الخدمة تطبيق تجريبي: فرق المعالجة وهمية ولا يُحال أي ملف إلى سلطة حقيقية.',
 now()),

('d0000000-0000-0000-0000-000000000003', 'terms',
 'Conditions d''utilisation', 'شروط الاستعمال',
 E'CivicCare Tunis est une application de démonstration destinée au signalement de problèmes urbains dans la ville de Tunis.\n\nEn utilisant ce service, vous vous engagez à :\n- ne signaler que des problèmes réels relevant de l''espace public ;\n- ne pas publier de données personnelles de tiers (visages, plaques, noms) dans les descriptions ou photos ;\n- ne pas utiliser le service pour des urgences : contactez directement les services de secours ;\n- ne pas envoyer de contenus illicites, diffamatoires ou hors sujet.\n\nLes signalements peuvent être reformulés, masqués ou refusés par la modération. Un signalement non publié reste traité.\n\nExploitant (démonstration) : [Exploitant à renseigner avant tout usage public].',
 E'سيفيك كير تونس تطبيق تجريبي مخصص للتبليغ عن المشاكل في الفضاء العمومي بمدينة تونس.\n\nباستعمالكم هذه الخدمة تلتزمون بـ:\n- التبليغ فقط عن مشاكل حقيقية تخص الفضاء العمومي؛\n- عدم نشر بيانات شخصية للغير (وجوه، لوحات، أسماء) في الأوصاف أو الصور؛\n- عدم استعمال الخدمة للحالات الطارئة: اتصلوا مباشرة بمصالح النجدة؛\n- عدم إرسال محتويات غير قانونية أو تشهيرية أو خارجة عن الموضوع.\n\nيمكن للمراجعة إعادة صياغة التبليغات أو حجبها أو رفضها. التبليغ غير المنشور يُعالج رغم ذلك.\n\nالمشغّل (تجريبي): [يجب تحديد المشغّل قبل أي استعمال عمومي].',
 now()),

('d0000000-0000-0000-0000-000000000004', 'privacy',
 'Confidentialité', 'الخصوصية',
 E'Données collectées :\n- position et description du problème (publiées après modération) ;\n- votre e-mail et, si vous le donnez, votre téléphone (jamais publiés) ;\n- la plaque d''un véhicule hors d''usage si vous la renseignez (jamais publiée) ;\n- photos jointes (publiées uniquement après approbation, métadonnées EXIF supprimées).\n\nFinalités : traitement du signalement, notifications si vous les activez, statistiques internes agrégées.\n\nConservation (choix de démonstration configurables) : les dossiers clos sont archivés après 30 jours ; les données personnelles sont supprimées 90 jours après la clôture. Les abonnements sont supprimés avec le dossier auquel ils se rapportent.\n\nVos choix : l''abonnement e-mail exige une activation explicite et peut être résilié à tout moment par le lien de désinscription.\n\nCe texte décrit le fonctionnement de l''application de démonstration ; il ne constitue pas un engagement juridique d''un exploitant réel. Les exigences légales applicables en Tunisie (notamment la loi n° 2004-63 sur la protection des données personnelles) doivent être vérifiées par l''exploitant avant tout déploiement public.',
 E'البيانات المجمعة:\n- موقع المشكلة ووصفها (يُنشران بعد المراجعة)؛\n- بريدكم الإلكتروني، وهاتفكم إن أدخلتموه (لا يُنشران أبداً)؛\n- لوحة السيارة المهملة إن أدخلتموها (لا تُنشر أبداً)؛\n- الصور المرفقة (تُنشر فقط بعد الموافقة، مع حذف بيانات EXIF).\n\nالأغراض: معالجة التبليغ، الإشعارات إن فعّلتموها، إحصائيات داخلية مجمعة.\n\nالحفظ (خيارات تجريبية قابلة للتعديل): تُؤرشف الملفات المغلقة بعد 30 يوماً؛ وتُحذف البيانات الشخصية بعد 90 يوماً من الإغلاق. تُحذف الاشتراكات مع الملف المتعلقة به.\n\nخياراتكم: يتطلب الاشتراك بالبريد تفعيلاً صريحاً ويمكن إلغاؤه في أي وقت عبر رابط إلغاء الاشتراك.\n\nيصف هذا النص عمل التطبيق التجريبي ولا يشكل التزاماً قانونياً لمشغّل حقيقي. يجب على المشغّل التحقق من المقتضيات القانونية في تونس (خاصة القانون عدد 63 لسنة 2004 المتعلق بحماية المعطيات الشخصية) قبل أي نشر عمومي.',
 now()),

('d0000000-0000-0000-0000-000000000005', 'legal',
 'Mentions légales', 'البيانات القانونية',
 E'CivicCare Tunis — application de démonstration.\n\nÉditeur : [Exploitant à renseigner avant tout usage public].\nHébergement : [Hébergeur à renseigner].\nContact : via le formulaire de contact du service.\n\nCe service n''est pas un service officiel de la municipalité de Tunis et n''a aucune affiliation institutionnelle. Les équipes de traitement présentées sont fictives.\n\nFond de carte : © contributeurs OpenStreetMap (licence ODbL). Périmètre géographique dérivé d''OpenStreetMap (relation 8896976), non officiel.',
 E'سيفيك كير تونس — تطبيق تجريبي.\n\nالناشر: [يجب تحديد المشغّل قبل أي استعمال عمومي].\nالاستضافة: [يجب تحديد المستضيف].\nالاتصال: عبر نموذج الاتصال بالخدمة.\n\nهذه الخدمة ليست خدمة رسمية لبلدية تونس وليست لها أي صفة مؤسسية. فرق المعالجة المعروضة وهمية.\n\nخلفية الخريطة: © مساهمو OpenStreetMap (رخصة ODbL). المحيط الجغرافي مشتق من OpenStreetMap (العلاقة 8896976) وهو غير رسمي.',
 now()),

('d0000000-0000-0000-0000-000000000006', 'accessibility',
 'Accessibilité', 'إمكانية الوصول',
 E'CivicCare Tunis vise le niveau WCAG 2.2 AA : navigation clavier complète, focus visible, libellés de formulaires, annonces d''erreurs, contrastes vérifiés et cibles tactiles d''au moins 44 px.\n\nLa carte interactive dispose d''une alternative : la liste des signalements offre les mêmes informations et les mêmes filtres. La position d''un signalement peut être saisie sans carte, par recherche d''adresse ou coordonnées.\n\nCette déclaration décrit une cible de conception vérifiée manuellement sur les parcours principaux ; aucune certification n''a été délivrée. Si vous rencontrez un obstacle, signalez-le via le formulaire de contact.',
 E'يستهدف سيفيك كير تونس مستوى WCAG 2.2 AA: تصفح كامل بلوحة المفاتيح، تركيز مرئي، تسميات للنماذج، إعلان عن الأخطاء، تباين متحقق منه وأهداف لمس لا تقل عن 44 بكسل.\n\nللخريطة التفاعلية بديل: قائمة التبليغات توفر نفس المعلومات ونفس عوامل التصفية. يمكن إدخال موقع التبليغ دون خريطة، بالبحث عن عنوان أو بالإحداثيات.\n\nيصف هذا الإعلان هدف تصميم تم التحقق منه يدوياً على المسارات الرئيسية؛ لم تُمنح أي شهادة. إذا واجهتم عائقاً، أبلغونا عبر نموذج الاتصال.',
 now()),

('d0000000-0000-0000-0000-000000000007', 'api',
 'API et données ouvertes', 'الواجهة البرمجية والبيانات المفتوحة',
 E'CivicCare Tunis expose une API de lecture compatible avec le sous-ensemble GET du standard Open311 GeoReport v2. Elle publie uniquement les signalements publiés, sans données personnelles.\n\nEndpoints :\n- GET /api/georeport/v2/services.json (ou .xml) : catalogue des types.\n- GET /api/georeport/v2/requests.json (ou .xml) : signalements, filtres service_code, start_date, end_date, status ; plage maximale de 90 jours (défaut : 90 derniers jours).\n- GET /api/georeport/v2/requests/{reference}.json (ou .xml) : détail d''un signalement.\n\nJuridiction applicative : tunis (identifiant de démonstration, non attribué officiellement). Statuts : open (ouvert, en traitement) et closed (traité/intervention commandée, hors compétence). La création de signalements par l''API Open311 (POST) n''est pas implémentée : ce service n''annonce pas une conformité intégrale GeoReport v2.\n\nExemple : /api/georeport/v2/requests.json?status=open&jurisdiction_id=tunis',
 E'يوفر سيفيك كير تونس واجهة قراءة متوافقة مع مجموعة GET من معيار Open311 GeoReport v2. تنشر فقط التبليغات المنشورة، دون بيانات شخصية.\n\nنقاط النفاذ:\n- GET /api/georeport/v2/services.json (أو .xml): فهرس الأنواع.\n- GET /api/georeport/v2/requests.json (أو .xml): التبليغات، مع عوامل التصفية service_code وstart_date وend_date وstatus؛ المدة القصوى 90 يوماً (الافتراضي: آخر 90 يوماً).\n- GET /api/georeport/v2/requests/{reference}.json (أو .xml): تفاصيل تبليغ.\n\nالولاية التطبيقية: tunis (معرّف تجريبي غير مسند رسمياً). الحالات: open (مفتوح، قيد المعالجة) وclosed (تمت المعالجة/صدر أمر بالتدخل، خارج الاختصاص). إنشاء التبليغات عبر Open311 (POST) غير متوفر: لا تدعي هذه الخدمة توافقاً كاملاً مع GeoReport v2.\n\nمثال: /api/georeport/v2/requests.json?status=open&jurisdiction_id=tunis',
 now());
